image: ruby:2.3

before_script:
  - gem install asciidoctor

pages:
  stage: deploy
  script:
  - make -C docs
  artifacts:
    paths:
    - public
  only:
  - master
  - pages

# https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html
