= Hacking

This is mostly a collection of notes to self, on ideas of where to look at
interesting stuff. Eventually I will add, if needed, the typical notes on code
style, project structure, etc.

== 2DA files

- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/index.htm[General list
  of 2DA files where to find for tables to plot]
- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/wspecial.htm[Proficiency
  impact on damage, to-hit, speed]
- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/wspatck.htm[Attacks
  per round based on level (caution, oddities in it)]
- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/weapprof.htm[Allowed
  proficiency points per class/kit]
- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/clswpbon.htm[Whether a
  class gets bonus attack with proficiency, penalty when not proficiency, and
  APR rate for unarmed attacks]
- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/thiefscl.htm[Allowed
  thief skills per class/kit]
- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/thiefskl.htm[Starting
  thieving skills per class/kit]
- https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/strmod.htm[Modifiers
  to damage and hit according to Strength] and the complementary for
  https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/strmodex.htm[extraordinary
  Strength]

== Table/chart ideas

- Number of spells (and at which levels) per XP. As in, to see how many spells
  per day a Bard can cast, and at which level. Would be interesting to see the
  character level as well, to see the efficiency of spells like Remove Magic.
  Also remember to consider multi-classes, to see the number of spells per day
  of e.g. a Bard vs a Fighter/Mage.

- Number of HP per XP. As in Imoen at 20K XP is level 6, and with the bonus on
  Constitution, she has 48 HP, while a Cleric would be level 8, so without bonus
  from Constitution would have less HP.

- THAC0 per XP. Would be interesting to see the THAC0 of a Fighter/Mage vs Bard.
