= Moebius Toolkit

Moebius Tookit is an application to help players, modders, and hopefully even
developers of one of the best video games of all time, the Baldur's Gate saga
(based on Advanced Dungeons and Dragons 2nd edition, another very successful
product which also gave me much joy in my youth).

Given the richness, depth and complexity of the rules of these games, I ended up
starting this project, which is the home of a humble personal initiative to
address some issues:

. The lack of charts, specially interactive ones, of some interesting data for
power gamers or new players. Some excellent tables are provided by the
https://baldursgate.fandom.com/wiki/Baldur's_Gate_Wiki[Baldur's Gate wiki], but
there is a lot more room to fill.

. The lack of an editor for the saved game files (like ShadowKeeper or EEKeeper)
which works on Linux, that is in a maintained state, and with a suitable license.

. The (at a times) unsatisfactory experience of using NearInfinity (extremely
useful and with many features, but slow and sometimes buggy).

. The interest in programming and trying new technologies that complement what I
already do or have done for paid work, like trying out chart libraries or
https://en.wikipedia.org/wiki/WebAssembly[WebAssembly] for redistributing the
application to users, Test Driven Development, and learning about game
engines.

== The application

The application is called a "toolkit" because it contains different modules
grouped together, with features a bit loosely related:

* A damage calculator. This is the most mature, complete and feature rich part
  of the application, because it was first developed standalone, and it's the
  code that originated the more ambitious plan.

* A game browser and save game editor. This is the most ambitious part, and it's
  in fully vaporware state. There is an implementation of several Infinity
  Engine file formats with decent unit tests, but some more would have to be
  parsed to at least get to the point of editing a saved game, which is the
  first milestone goal.

* Other charts and calculators in half baked state, but which hopefully be
  complete in just some months, given that it's easy to do, and fairly
  rewarding.

See more about the application in the
https://moebiusproject.gitlab.io/moebius_toolkit[Moebius Toolkit website].

== The library

Many parts of the application are developed as a library to easy the unit
testing, and to be used with https://github.com/vgvassilev/cling[cling's REPL].
The long term plan (or, more likely, the pipe dream), is that the project could
get some traction, and hopefully be able to make the library useful for other
project.

== Roadmap and current status

The current status is almost vaporware, but useful enough to have a first public
release, and hopefully gain some users, and maybe even some developers. The
shared library has support for reading a few file formats of the engine, and
there is some extra code for representing dice rolls, calculating averages, etc.
And that's almost all of it. But to achieve the feature of just the very basic
opening of a saved game, modifying it in the UI, and saving it to disk, still
requires some more effort.

== Much more reading

This project is not only about an application, but also some focused articles
that don't fit elsewhere, including an extensive spell guide, and an analysis
done with the Damage Calculator.

https://moebiusproject.gitlab.io/[See much more at the website!]

